#****************************************************************************
#* jg_lint.py
#*
#* Copyright 2025 Matthew Ballance and Contributors
#*
#* Licensed under the Apache License, Version 2.0 (the "License"); you may
#* not use this file except in compliance with the License.
#* You may obtain a copy of the License at:
#*
#*   http://www.apache.org/licenses/LICENSE-2.0
#*
#* Unless required by applicable law or agreed to in writing, software
#* distributed under the License is distributed on an "AS IS" BASIS,
#* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#* See the License for the specific language governing permissions and
#* limitations under the License.
#*
#****************************************************************************
"""The JasperGold backend: build the command line, run it, parse the log.

JasperGold is invoked in superlint batch mode:

    jg -superlint -batch <tcl_script>

The Tcl script sets up the design, configures superlint depth, and runs
the check. The three profiles control the depth of analysis:

* ``basic`` -- default superlint (quick, structural checks only).
* ``default`` -- full superlint (elaborated checks enabled).
* ``strict`` -- all checks including advisory-level rules.

JasperGold does not support native waiver lowering; all waivers are
handled by the post-filter.

JasperGold is the property of its respective owners.
"""

import logging
import os
import time
from typing import List, Tuple

from .backends import ToolRequest, ToolRun
from .finding import Finding
from .util import exec_tool, tool_version
from . import jg_parser

_log = logging.getLogger("hdllint.jg")


PROFILES = {
    "basic":   [],
    "default": ["-superlint_full"],
    "strict":  ["-superlint_full", "-superlint_advisory"],
}


def _write_tcl(req: ToolRequest, tcl_path: str) -> None:
    """Write the Tcl script that drives the superlint run."""
    with open(tcl_path, "w") as fp:
        fp.write("# Auto-generated by hdllint jg backend\n")

        for incdir in req.incdirs:
            fp.write("analyze -incdir %s\n" % incdir)
        for define in req.defines:
            fp.write("analyze -define %s\n" % define)

        for f in req.files:
            fp.write("analyze -f %s\n" % f)

        if req.top:
            fp.write("elaborate -top %s\n" % req.top[0])

        fp.write("exit\n")


def build_cmd(req: ToolRequest, tcl_path: str) -> Tuple[List[str], List[str]]:
    """`(cmd, notes)`. Notes are Info-level things the user should be told."""
    notes: List[str] = []

    if req.profile not in PROFILES:
        raise ValueError(
            "Unknown lint profile '%s' for jaspergold. Available: %s."
            % (req.profile, ", ".join(sorted(PROFILES.keys()))))

    cmd = [req.exe or "jg", "-superlint", "-batch"]
    cmd.extend(PROFILES[req.profile])
    cmd.extend(req.args)
    cmd.append(tcl_path)

    if req.top:
        if len(req.top) > 1:
            notes.append(
                "jaspergold accepts one -top; elaborating '%s' and ignoring %s. "
                "Use a separate lint task per top to cover the others."
                % (req.top[0], ", ".join("'%s'" % t for t in req.top[1:])))
    else:
        notes.append(
            "jaspergold: no `top:` given, so the Tcl script omits "
            "`elaborate -top`. Checks that need elaboration may be incomplete.")

    return cmd, notes


async def run(ctxt, req: ToolRequest) -> Tuple[ToolRun, List[Finding], List[str]]:
    """Run JasperGold superlint over `req` and return `(run_info, findings, notes)`."""
    run_info = ToolRun(tool=jg_parser.TOOL_ID, name=jg_parser.TOOL_NAME)

    tcl_path = os.path.join(req.rundir, "superlint.tcl")
    _write_tcl(req, tcl_path)

    try:
        cmd, notes = build_cmd(req, tcl_path)
    except ValueError as e:
        run_info.error = str(e)
        return run_info, [], []

    run_info.cmd = cmd
    run_info.version = await tool_version(
        req.exe or "jg", ["-version"], req.env)

    # Write a shell script for reproducibility.
    with open(os.path.join(req.rundir, "lint.sh"), "w") as fp:
        fp.write("#!/bin/sh\n")
        for arg in cmd:
            fp.write("%s \\\n" % arg)

    start = time.time()
    status, log_path = await exec_tool(
        ctxt, cmd, req.rundir, "lint.log", req.env)
    run_info.duration = time.time() - start
    run_info.status = status
    run_info.log = log_path

    findings = jg_parser.parse_file(log_path, req.root)
    run_info.findings = len(findings)

    if status != 0 and not findings:
        run_info.error = (
            "jg exited %d and produced no parsable findings; see %s"
            % (status, log_path))

    return run_info, findings, notes
