#****************************************************************************
#* vcs_waivers.py
#*
#* Copyright 2025 Matthew Ballance and Contributors
#*
#* Licensed under the Apache License, Version 2.0 (the "License"); you may
#* not use this file except in compliance with the License.
#* You may obtain a copy of the License at:
#*
#*   http://www.apache.org/licenses/LICENSE-2.0
#*
#* Unless required by applicable law or agreed to in writing, software
#* distributed under the License is distributed on an "AS IS" BASIS,
#* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#* See the License for the specific language governing permissions and
#* limitations under the License.
#*
#****************************************************************************
"""Lowering `hdllint` waivers into VC Static's native SpyGlass-compatible
waiver format.

VC Static reads `.swl` (SpyGlass Waiver Language) files with directives of the
form:

    waive -rule {rule} -file {pattern} -comment "{reason}"

Lowering is partial by design.  `lower()` returns the waivers it took
responsibility for; everything it could not express is left to the post-filter,
which handles it exactly.  Four things VC Static's waiver syntax cannot
express, each left behind deliberately:

* a glob in `rule` -- `-rule` takes one rule name;
* a waiver scoped to a different tool;
* a `path` that is a bare basename -- our matcher also matches basenames, and
  `-file "*name.v"` would additionally match `othername.v`;
* a waiver with no `rule`, i.e. one written for a message that has no rule id.
"""

import os
from typing import List, Optional, Tuple

from .waiver import Waiver

GLOB_CHARS = "*?[]"

CONFIG_FILE = "waivers.swl"


def _lowerable(w: Waiver) -> bool:
    if w.tool and w.tool not in ("vcs", "vc_static"):
        return False
    if not w.rule or any(c in w.rule for c in GLOB_CHARS):
        return False
    if w.path and "/" not in w.path.replace(os.sep, "/"):
        return False
    return True


def _file_pattern(path: str, root: str) -> str:
    """A waiver path as VC Static will see it.

    VC Static matches against filenames as they appear on its command line,
    which is absolute here, while waiver paths are relative to the project
    root.  Anchoring the pattern at the root keeps the two aligned.
    """
    p = path.replace(os.sep, "/")
    if os.path.isabs(p) or not root:
        return p
    return "%s/%s" % (root.replace(os.sep, "/").rstrip("/"), p)


def config_text(waivers: List[Waiver], root: str = "") -> str:
    """The `.swl` file body for the lowerable subset of `waivers`."""
    lines = [
        "// Generated by dv-flow-libhdllint from the project waiver file.",
        "// Do not edit: edit the waiver source and re-run lint.",
        "",
    ]
    for w in waivers:
        if not _lowerable(w):
            continue
        parts = ["waive", "-rule", w.rule]
        if w.path:
            parts.extend(["-file", _file_pattern(w.path, root)])
        parts.extend(["-comment", '"%s"' % w.reason])
        lines.append(" ".join(parts))
    return "\n".join(lines) + "\n"


def lower(waivers: List[Waiver], req) -> Tuple[List[str], List[Waiver]]:
    """Write the config file and return `(extra_args, lowered)`.

    `lowered` is the subset VC Static now suppresses itself; the caller leaves
    the rest to the post-filter.  When nothing is lowerable no file is written
    and no argument is added, so the command line stays exactly what it would
    have been.
    """
    lowered = [w for w in waivers if _lowerable(w)]
    if not lowered:
        return [], []

    path = os.path.join(req.rundir, CONFIG_FILE)
    with open(path, "w") as fp:
        fp.write(config_text(waivers, req.root))

    return [path], lowered
