#****************************************************************************
#* vcs_lint.py
#*
#* Copyright 2025 Matthew Ballance and Contributors
#*
#* Licensed under the Apache License, Version 2.0 (the "License"); you may
#* not use this file except in compliance with the License.
#* You may obtain a copy of the License at:
#*
#*   http://www.apache.org/licenses/LICENSE-2.0
#*
#* Unless required by applicable law or agreed to in writing, software
#* distributed under the License is distributed on an "AS IS" BASIS,
#* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#* See the License for the specific language governing permissions and
#* limitations under the License.
#*
#****************************************************************************
"""The VC Static backend: build a TCL script, run it, parse the log.

VC Static is invoked through `vc_static_shell` with a TCL control script.
The shell reads a project file, sets up the design, runs the selected goal,
and writes a SpyGlass-compatible report that `vcs_parser` consumes.

Profiles map to VC Static goals that mirror SpyGlass's goal hierarchy:

| profile   | goal                 |
|-----------|----------------------|
| `basic`   | `lint_turbo_rtl`     |
| `default` | `lint_rtl`           |
| `strict`  | `lint_rtl_enhanced`  |

What VC Static sees: both the synthesis subset (RTL) and style rules. It
implements both `Rtl` and `Style` families, because its goal system covers
both categories in a single run.
"""

import logging
import os
import time
from typing import List, Tuple

from .backends import ToolRequest, ToolRun
from .finding import Finding
from .util import exec_tool, tool_version
from . import vcs_parser

_log = logging.getLogger("hdllint.vcs")


# Profiles map to VC Static goals (SpyGlass-compatible naming).
PROFILES = {
    "basic":   "lint_turbo_rtl",
    "default": "lint_rtl",
    "strict":  "lint_rtl_enhanced",
}


def _write_tcl(req: ToolRequest, goal: str) -> str:
    """Write the TCL control script and return its path."""
    tcl_path = os.path.join(req.rundir, "lint.tcl")

    lines = [
        "# Generated by dv-flow-libhdllint -- do not edit.",
        "set_option projectwdir %s" % req.rundir,
    ]

    if req.top:
        lines.append("set_option top %s" % req.top[0])

    for incdir in req.incdirs:
        lines.append("set_option incdir %s" % incdir)
    for define in req.defines:
        lines.append("set_option define %s" % define)

    for f in req.files:
        lines.append("read_file -type verilog %s" % f)

    lines.append("current_goal %s" % goal)
    lines.append("run_goal")
    lines.append("write_report spyglass")
    lines.append("exit")

    with open(tcl_path, "w") as fp:
        fp.write("\n".join(lines) + "\n")

    return tcl_path


def build_cmd(req: ToolRequest) -> Tuple[List[str], List[str]]:
    """`(cmd, notes)`. Notes are Info-level things the user should be told."""
    notes: List[str] = []

    if req.profile not in PROFILES:
        raise ValueError(
            "Unknown lint profile '%s' for vc_static. Available: %s."
            % (req.profile, ", ".join(sorted(PROFILES.keys()))))

    goal = PROFILES[req.profile]
    tcl_path = _write_tcl(req, goal)

    cmd = [req.exe or "vc_static_shell", "-f", tcl_path]
    cmd.extend(req.args)

    if req.top and len(req.top) > 1:
        notes.append(
            "vc_static accepts one top module; linting '%s' and ignoring %s. "
            "Use a separate lint task per top to cover the others."
            % (req.top[0], ", ".join("'%s'" % t for t in req.top[1:])))

    if not req.top:
        notes.append(
            "vc_static: no `top:` given, so the design is linted without a "
            "specified top. Checks that need elaboration are only as good as "
            "the top VC Static infers.")

    return cmd, notes


async def run(ctxt, req: ToolRequest) -> Tuple[ToolRun, List[Finding], List[str]]:
    """Run VC Static over `req` and return `(run_info, findings, notes)`."""
    run_info = ToolRun(tool=vcs_parser.TOOL_ID, name=vcs_parser.TOOL_NAME)

    try:
        cmd, notes = build_cmd(req)
    except ValueError as e:
        run_info.error = str(e)
        return run_info, [], []

    run_info.cmd = cmd
    run_info.version = await tool_version(
        req.exe or "vc_static_shell", ["-version"], req.env)

    start = time.time()
    status, log_path = await exec_tool(
        ctxt, cmd, req.rundir, "lint.log", req.env)
    run_info.duration = time.time() - start
    run_info.status = status
    run_info.log = log_path

    findings = vcs_parser.parse_file(log_path, req.root)
    run_info.findings = len(findings)

    if status != 0 and not findings:
        run_info.error = (
            "vc_static exited %d and produced no parsable findings; see %s"
            % (status, log_path))

    return run_info, findings, notes
