#****************************************************************************
#* vlt_waivers.py
#*
#* Copyright 2025 Matthew Ballance and Contributors
#*
#* Licensed under the Apache License, Version 2.0 (the "License"); you may
#* not use this file except in compliance with the License.
#* You may obtain a copy of the License at:
#*
#*   http://www.apache.org/licenses/LICENSE-2.0
#*
#* Unless required by applicable law or agreed to in writing, software
#* distributed under the License is distributed on an "AS IS" BASIS,
#* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#* See the License for the specific language governing permissions and
#* limitations under the License.
#*
#****************************************************************************
"""Lowering `hdllint` waivers into a Verilator configuration file.

The library has ONE waiver format (waiver.py). This module translates the
subset of it that Verilator can express natively into a `.vlt` config file:

    `verilator_config
    lint_off -rule WIDTHEXPAND -file "/proj/packages/wb_dma/rtl/verilog/*"
    lint_off -rule LATCH -file "/proj/rtl/a.v" -lines 142

Lowering is a real capability, not a reformatting exercise, and the reason to
have it is that the tool then never spends time on the check and its own log
stays readable. What it costs is reporting: a natively suppressed finding is
never emitted, so it cannot be counted as waived, and a waiver that no longer
matches anything cannot be detected as stale. That is why lowering is opt-in
(`waiver_mode: native`) and why the runner reports lowered waivers separately
from waived findings rather than pretending the two are the same number.

**Partial lowering is the normal case, and is the point.** `lower()` returns
the waivers it took responsibility for; everything it could not express is
left to the post-filter, which handles it exactly. So `native` never means
"some waivers silently stopped working". Four things Verilator cannot express,
each left behind deliberately:

* a glob in `rule` -- Verilator's `-rule` takes one rule name;
* a waiver scoped to a different tool;
* a `path` that is a bare basename -- our matcher also matches basenames,
  and `-file "*name.v"` would additionally match `othername.v`;
* a waiver with no `rule`, i.e. one written for a message that has no rule id
  (a Verilator syntax error). `lint_off` cannot suppress those at all.
"""

import os
from typing import List, Optional, Tuple

from .waiver import Waiver

GLOB_CHARS = "*?[]"

CONFIG_FILE = "waivers.vlt"


def _lowerable(w : Waiver) -> bool:
    if w.tool and w.tool not in ("vlt", "verilator"):
        return False
    if not w.rule or any(c in w.rule for c in GLOB_CHARS):
        # `-rule` takes exactly one rule name. A glob would have to be
        # expanded against Verilator's rule list, which moves every release.
        return False
    if w.path and "/" not in w.path.replace(os.sep, "/"):
        # A bare basename. Our matcher accepts it; `-file "*a.v"` would also
        # match `bba.v`, so lowering it would suppress more than was asked.
        return False
    return True


def _file_pattern(path : str, root : str) -> str:
    """A waiver path as Verilator will see it.

    Verilator matches against the filename as it appears on ITS command line,
    which is absolute here, while waiver paths are relative to the project
    root. Anchoring the pattern at the root keeps the two the same match --
    a bare `rtl/*` would match nothing at all.
    """
    p = path.replace(os.sep, "/")
    if os.path.isabs(p) or not root:
        return p
    return "%s/%s" % (root.replace(os.sep, "/").rstrip("/"), p)


def config_text(waivers : List[Waiver], root : str = "") -> str:
    """The `.vlt` file body for the lowerable subset of `waivers`."""
    lines = ["`verilator_config",
             "// Generated by dv-flow-libhdllint from the project waiver file.",
             "// Do not edit: edit the waiver source and re-run lint.",
             ""]
    for w in waivers:
        if not _lowerable(w):
            continue
        parts = ["lint_off", "-rule", w.rule]
        if w.path:
            parts.extend(["-file", '"%s"' % _file_pattern(w.path, root)])
        if w.line >= 0:
            parts.extend(["-lines", str(w.line)])
        # The reason travels with the rule: someone reading the generated file
        # (or a Verilator log that references it) should not have to go find
        # the source waiver to learn why the check is off.
        lines.append("%s  // %s" % (" ".join(parts), w.reason))
    return "\n".join(lines) + "\n"


def lower(waivers : List[Waiver], req) -> Tuple[List[str], List[Waiver]]:
    """Write the config file and return `(extra_args, lowered)`.

    `lowered` is the subset Verilator now suppresses itself; the caller leaves
    the rest to the post-filter. When nothing is lowerable no file is written
    and no argument is added, so the command line stays exactly what it would
    have been.
    """
    lowered = [w for w in waivers if _lowerable(w)]
    if not lowered:
        return [], []

    path = os.path.join(req.rundir, CONFIG_FILE)
    with open(path, "w") as fp:
        fp.write(config_text(waivers, req.root))

    # A `.vlt` file is passed like a source file; Verilator recognizes it by
    # its `verilator_config` header.
    return [path], lowered
